services:
  postgres:
    image: postgres:16-alpine
    container_name: ledger-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ledger-backend

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ledger
      PORT: 3000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000

    container_name: ledger-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres_data:
